pipelines:
  default:
    - step:
        name: Sync Bitbucket to GitHub
        image: alpine/git
        script:
          - git config --global user.email "sync@bitbucket.com"
          - git config --global user.name "Bitbucket Sync Bot"
          - git clone --mirror https://navivarma@bitbucket.org/bhshilpa2/trace_sample.git bitbucket-mirror
          - cd bitbucket-mirror
          - git push --mirror https://x-access-token:${GITHUB_TOKEN}@github.com/bhshilpa2708/trace_sample.git
